version: '3.8'

# create volume: mini-project-db  
volumes:
  mini-project-db:
    name: mini-project-db

services:
  # service 1
  mini-project-db:
    container_name: mini-project-db
    image: mysql:8
    # Restart policy, will be restarted when the app fails to run.
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=exercise_sql
    volumes:
      - mini-project-db:/var/lib/mysql

  # service 2
  mini-project-app:
    container_name: mini-project-app
    image: tobialbertino/mini-project:v1
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # Restart policy, will be restarted when the app fails to run.
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mini-project-db
    env_file:
      - .env
    # overwrite .env 
    environment:
      - DB_HOST=mini-project-db
