version: '3'

services:
  # service 1
  app:
    container_name: app-mini-project
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db

  # service 2
  db:
    container_name: db-mini-project
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=exercise_sql
    volumes:
      - contoh-db:/var/lib/mysql
volumes:
  contoh-db:
